# Generated by Django 3.0.2 on 2020-04-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_desc', models.TextField()),
                ('prod_price', models.PositiveIntegerField()),
                ('prod_img', models.ImageField(default='image.jpg', upload_to='')),
                ('prod_rating', models.IntegerField()),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prod_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
