# Generated by Django 3.0.2 on 2020-04-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_img',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_rating',
            new_name='product_rating',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_seller',
            new_name='product_seller',
        ),
    ]
