# Generated by Django 3.0.2 on 2020-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200404_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='abc.jpg', upload_to='product_images'),
        ),
    ]
