# Generated by Django 3.0.5 on 2020-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(default='stripechargeid', max_length=50),
            preserve_default=False,
        ),
    ]
