# Generated by Django 3.0.5 on 2020-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200422_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_tag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_mrp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
