# Generated by Django 3.0.5 on 2020-04-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200424_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_tag',
        ),
    ]
